-- Replace all instances of XXX with the external site db password (same one as in ../application/config/auth.php).
-- Uncomment all entries.

--GRANT SELECT ON         web.cv_section       TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.cv               TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.lang             TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.license          TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.text             TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project          TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project_type     TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project_tag      TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project_url      TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project_url_type TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project_image    TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.project_tag      TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT, INSERT ON web.project_comment  TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.settings         TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT ON         web.share            TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT, INSERT ON web.stat_view        TO 'w'@'localhost' IDENTIFIED BY 'XXX';
--GRANT SELECT, INSERT ON web.stat_visit       TO 'w'@'localhost' IDENTIFIED BY 'XXX';
