-- AVAILABLE LANGUAGES
INSERT INTO lang VALUES ('es', 'Castellano', '1');
INSERT INTO lang VALUES ('en', 'English', '1');
INSERT INTO lang VALUES ('eu', 'Euskara', '1');

-- DATE ELEMENTS
INSERT INTO text VALUES ('MONTH_01', 'es', 'DATE', 'enero', null);
INSERT INTO text VALUES ('MONTH_01', 'en', 'DATE', 'January', null);
INSERT INTO text VALUES ('MONTH_01', 'eu', 'DATE', 'urtarrila', null);
INSERT INTO text VALUES ('MONTH_02', 'es', 'DATE', 'febrero', null);
INSERT INTO text VALUES ('MONTH_02', 'en', 'DATE', 'February', null);
INSERT INTO text VALUES ('MONTH_02', 'eu', 'DATE', 'otsaila', null);
INSERT INTO text VALUES ('MONTH_03', 'es', 'DATE', 'marzo', null);
INSERT INTO text VALUES ('MONTH_03', 'en', 'DATE', 'March', null);
INSERT INTO text VALUES ('MONTH_03', 'eu', 'DATE', 'martxoa', null);
INSERT INTO text VALUES ('MONTH_04', 'es', 'DATE', 'abril', null);
INSERT INTO text VALUES ('MONTH_04', 'en', 'DATE', 'April', null);
INSERT INTO text VALUES ('MONTH_04', 'eu', 'DATE', 'apirila', null);
INSERT INTO text VALUES ('MONTH_05', 'es', 'DATE', 'mayo', null);
INSERT INTO text VALUES ('MONTH_05', 'en', 'DATE', 'May', null);
INSERT INTO text VALUES ('MONTH_05', 'eu', 'DATE', 'maiatza', null);
INSERT INTO text VALUES ('MONTH_06', 'es', 'DATE', 'junio', null);
INSERT INTO text VALUES ('MONTH_06', 'en', 'DATE', 'June', null);
INSERT INTO text VALUES ('MONTH_06', 'eu', 'DATE', 'ekaina', null);
INSERT INTO text VALUES ('MONTH_07', 'es', 'DATE', 'julio', null);
INSERT INTO text VALUES ('MONTH_07', 'en', 'DATE', 'July', null);
INSERT INTO text VALUES ('MONTH_07', 'eu', 'DATE', 'uztaila', null);
INSERT INTO text VALUES ('MONTH_08', 'es', 'DATE', 'agosto', null);
INSERT INTO text VALUES ('MONTH_08', 'en', 'DATE', 'August', null);
INSERT INTO text VALUES ('MONTH_08', 'eu', 'DATE', 'abuztua', null);
INSERT INTO text VALUES ('MONTH_09', 'es', 'DATE', 'septiembre', null);
INSERT INTO text VALUES ('MONTH_09', 'en', 'DATE', 'September', null);
INSERT INTO text VALUES ('MONTH_09', 'eu', 'DATE', 'iraila', null);
INSERT INTO text VALUES ('MONTH_10', 'es', 'DATE', 'octubre', null);
INSERT INTO text VALUES ('MONTH_10', 'en', 'DATE', 'October', null);
INSERT INTO text VALUES ('MONTH_10', 'eu', 'DATE', 'urria', null);
INSERT INTO text VALUES ('MONTH_11', 'es', 'DATE', 'noviembre', null);
INSERT INTO text VALUES ('MONTH_11', 'en', 'DATE', 'November', null);
INSERT INTO text VALUES ('MONTH_11', 'eu', 'DATE', 'azaroa', null);
INSERT INTO text VALUES ('MONTH_12', 'es', 'DATE', 'diciembre', null);
INSERT INTO text VALUES ('MONTH_12', 'en', 'DATE', 'December', null);
INSERT INTO text VALUES ('MONTH_12', 'eu', 'DATE', 'abendua', null);
INSERT INTO text VALUES ('DAY_1', 'es', 'DATE', 'lunes', null);
INSERT INTO text VALUES ('DAY_1', 'en', 'DATE', 'Monday', null);
INSERT INTO text VALUES ('DAY_1', 'eu', 'DATE', 'astelehena', null);
INSERT INTO text VALUES ('DAY_2', 'es', 'DATE', 'martes', null);
INSERT INTO text VALUES ('DAY_2', 'en', 'DATE', 'Tuesday', null);
INSERT INTO text VALUES ('DAY_2', 'eu', 'DATE', 'asteartea', null);
INSERT INTO text VALUES ('DAY_3', 'es', 'DATE', 'miércoles', null);
INSERT INTO text VALUES ('DAY_3', 'en', 'DATE', 'Wednesday', null);
INSERT INTO text VALUES ('DAY_3', 'eu', 'DATE', 'astezkena', null);
INSERT INTO text VALUES ('DAY_4', 'es', 'DATE', 'jueves', null);
INSERT INTO text VALUES ('DAY_4', 'en', 'DATE', 'Thursday', null);
INSERT INTO text VALUES ('DAY_4', 'eu', 'DATE', 'osteguna', null);
INSERT INTO text VALUES ('DAY_5', 'es', 'DATE', 'viernes', null);
INSERT INTO text VALUES ('DAY_5', 'en', 'DATE', 'Friday', null);
INSERT INTO text VALUES ('DAY_5', 'eu', 'DATE', 'ostirala', null);
INSERT INTO text VALUES ('DAY_6', 'es', 'DATE', 'sábado', null);
INSERT INTO text VALUES ('DAY_6', 'en', 'DATE', 'Saturday', null);
INSERT INTO text VALUES ('DAY_6', 'eu', 'DATE', 'larunbata', null);
INSERT INTO text VALUES ('DAY_7', 'es', 'DATE', 'domingo', null);
INSERT INTO text VALUES ('DAY_7', 'en', 'DATE', 'Sunday', null);
INSERT INTO text VALUES ('DAY_7', 'eu', 'DATE', 'igandea', null);

-- SECTIONS
INSERT INTO text VALUES ('SECTION_HOME', 'es', 'SECTION', 'Inicio', null);
INSERT INTO text VALUES ('SECTION_HOME', 'en', 'SECTION', 'Home', null);
INSERT INTO text VALUES ('SECTION_HOME', 'eu', 'SECTION', 'Hasiera', null);
INSERT INTO text VALUES ('SECTION_ME', 'es', 'SECTION', 'Yo', null);
INSERT INTO text VALUES ('SECTION_ME', 'en', 'SECTION', 'Me', null);
INSERT INTO text VALUES ('SECTION_ME', 'eu', 'SECTION', 'Ni', null);
INSERT INTO text VALUES ('SECTION_PROJECTS', 'es', 'SECTION', 'Proyectos', null);
INSERT INTO text VALUES ('SECTION_PROJECTS', 'en', 'SECTION', 'Projects', null);
INSERT INTO text VALUES ('SECTION_PROJECTS', 'eu', 'SECTION', 'Proiektuak', null);

-- SOCIAL
INSERT INTO text VALUES ('SOCIAL_FACEBOOK', 'es', 'SOCIAL', 'Visita mi perfil en Facebook.', null);
INSERT INTO text VALUES ('SOCIAL_FACEBOOK', 'en', 'SOCIAL', 'Check out my Facebook profile.', null);
INSERT INTO text VALUES ('SOCIAL_FACEBOOK', 'eu', 'SOCIAL', 'Begiratu nire Facebook profila.', null);
INSERT INTO text VALUES ('SOCIAL_X', 'es', 'SOCIAL', 'Visita mi perfil en X.', null);
INSERT INTO text VALUES ('SOCIAL_X', 'en', 'SOCIAL', 'Check out my X profile.', null);
INSERT INTO text VALUES ('SOCIAL_X', 'eu', 'SOCIAL', 'Begiratu nire X profila.', null);
INSERT INTO text VALUES ('SOCIAL_INSTAGRAM', 'es', 'SOCIAL', 'Visita mi perfil en Instagram.', null);
INSERT INTO text VALUES ('SOCIAL_INSTAGRAM', 'en', 'SOCIAL', 'Check out my Instagram profile.', null);
INSERT INTO text VALUES ('SOCIAL_INSTAGRAM', 'eu', 'SOCIAL', 'Begiratu nire Instagram profila.', null);
INSERT INTO text VALUES ('SOCIAL_TELEGRAM', 'es', 'SOCIAL', 'Contáctame en Telegram.', null);
INSERT INTO text VALUES ('SOCIAL_TELEGRAM', 'en', 'SOCIAL', 'Contact me on Telegram.', null);
INSERT INTO text VALUES ('SOCIAL_TELEGRAM', 'eu', 'SOCIAL', 'Bidali mezu bat Telegram-en.', null);
INSERT INTO text VALUES ('SOCIAL_LINKEDIN', 'es', 'SOCIAL', 'Visita mi perfil en LinkedIn.', null);
INSERT INTO text VALUES ('SOCIAL_LINKEDIN', 'en', 'SOCIAL', 'Check out my LinkedIn profile.', null);
INSERT INTO text VALUES ('SOCIAL_LINKEDIN', 'eu', 'SOCIAL', 'Begiratu nire LinkedId profila.', null);
INSERT INTO text VALUES ('SOCIAL_VKONTAKTE', 'es', 'SOCIAL', 'Visita mi perfil en VKontakte', null);
INSERT INTO text VALUES ('SOCIAL_VKONTAKTE', 'en', 'SOCIAL', 'Check out my VKontakte profile', null);
INSERT INTO text VALUES ('SOCIAL_VKONTAKTE', 'eu', 'SOCIAL', 'Begiratu nire LinkedId profila.', null);
INSERT INTO text VALUES ('SOCIAL_GITHUB', 'es', 'SOCIAL', 'Visita mi perfil en GitHub.', null);
INSERT INTO text VALUES ('SOCIAL_GITHUB', 'en', 'SOCIAL', 'Check out my GitHub profile.', null);
INSERT INTO text VALUES ('SOCIAL_GITHUB', 'eu', 'SOCIAL', 'Begiratu nire GitHub profila.', null);
INSERT INTO text VALUES ('SOCIAL_GITLAB', 'es', 'SOCIAL', 'Visita mi perfil en GitLab.', null);
INSERT INTO text VALUES ('SOCIAL_GITLAB', 'en', 'SOCIAL', 'Check out my GitLab profile.', null);
INSERT INTO text VALUES ('SOCIAL_GITLAB', 'eu', 'SOCIAL', 'Begiratu nire GitLab profila.', null);
INSERT INTO text VALUES ('SOCIAL_WEB', 'es', 'SOCIAL', 'Visita mi sitio web.', null);
INSERT INTO text VALUES ('SOCIAL_WEB', 'en', 'SOCIAL', 'Check out my website.', null);
INSERT INTO text VALUES ('SOCIAL_WEB', 'eu', 'SOCIAL', 'Begiratu nire webgunea.', null);
INSERT INTO social VALUES (1, 'Facebook', 'https://facebook.com/', 'facebook.svg', 'SOCIAL_FACEBOOK');
INSERT INTO social VALUES (2, 'X', 'https://x.com/', 'x.svg', 'SOCIAL_X');
INSERT INTO social VALUES (3, 'Instagram', 'https://instagram.com/', 'instagram.svg', 'SOCIAL_INSTAGRAM');
INSERT INTO social VALUES (4, 'Telegram', 'https://telegram.com/', 'telegram.svg', 'SOCIAL_TELEGRAM');
INSERT INTO social VALUES (5, 'LinkedIn', 'https://linkedin.com/', 'linkedin.svg', 'SOCIAL_LINKEDIN');
INSERT INTO social VALUES (6, 'VKontakte', 'https://vkontakte.com/', 'vkontakte.svg', 'SOCIAL_VKONTAKTE');
INSERT INTO social VALUES (7, 'GitHub', 'https://github.com/', 'github.svg', 'SOCIAL_GITHUB');
INSERT INTO social VALUES (8, 'GitLab', 'https://gitlab.com/', 'gitlab.svg', 'SOCIAL_GITLAB');
INSERT INTO social VALUES (9, 'Web', null, 'web.svg', 'SOCIAL_WEB');

-- SHARE
INSERT INTO text VALUES ('SHARE_FACEBOOK', 'es', 'SHARE', 'Facebook', null);
INSERT INTO text VALUES ('SHARE_FACEBOOK', 'en', 'SHARE', 'Facebook', null);
INSERT INTO text VALUES ('SHARE_FACEBOOK', 'eu', 'SHARE', 'Facebook', null);
INSERT INTO text VALUES ('SHARE_X', 'es', 'SHARE', 'X', null);
INSERT INTO text VALUES ('SHARE_X', 'en', 'SHARE', 'X', null);
INSERT INTO text VALUES ('SHARE_X', 'eu', 'SHARE', 'X', null);
INSERT INTO text VALUES ('SHARE_TELEGRAM', 'es', 'SHARE', 'Telegram', null);
INSERT INTO text VALUES ('SHARE_TELEGRAM', 'en', 'SHARE', 'Telegram', null);
INSERT INTO text VALUES ('SHARE_TELEGRAM', 'eu', 'SHARE', 'Telegram', null);
INSERT INTO text VALUES ('SHARE_LINKEDIN', 'es', 'SHARE', 'LinkedIn', null);
INSERT INTO text VALUES ('SHARE_LINKEDIN', 'en', 'SHARE', 'LinkedIn', null);
INSERT INTO text VALUES ('SHARE_LINKEDIN', 'eu', 'SHARE', 'LinkedIn', null);
INSERT INTO text VALUES ('SHARE_VKONTAKTE', 'es', 'SHARE', 'VKontakte', null);
INSERT INTO text VALUES ('SHARE_VKONTAKTE', 'en', 'SHARE', 'VKontakte', null);
INSERT INTO text VALUES ('SHARE_VKONTAKTE', 'eu', 'SHARE', 'VKontakte', null);
INSERT INTO text VALUES ('SHARE_FACEBOOK_DESC', 'es', 'SHARE', 'Publicar en Facebook', null);
INSERT INTO text VALUES ('SHARE_FACEBOOK_DESC', 'en', 'SHARE', 'Share on Facebook', null);
INSERT INTO text VALUES ('SHARE_FACEBOOK_DESC', 'eu', 'SHARE', 'Facebook', null);
INSERT INTO text VALUES ('SHARE_X_DESC', 'es', 'SHARE', 'Publicar en X', null);
INSERT INTO text VALUES ('SHARE_X_DESC', 'en', 'SHARE', 'Share on X', null);
INSERT INTO text VALUES ('SHARE_X_DESC', 'eu', 'SHARE', 'X', null);
INSERT INTO text VALUES ('SHARE_TELEGRAM_DESC', 'es', 'SHARE', 'Publicar en Telegram', null);
INSERT INTO text VALUES ('SHARE_TELEGRAM_DESC', 'en', 'SHARE', 'Share on Telegram', null);
INSERT INTO text VALUES ('SHARE_TELEGRAM_DESC', 'eu', 'SHARE', 'Telegram', null);
INSERT INTO text VALUES ('SHARE_LINKEDIN_DESC', 'es', 'SHARE', 'Publicar en LinkedIn', null);
INSERT INTO text VALUES ('SHARE_LINKEDIN_DESC', 'en', 'SHARE', 'Share on LinkedIn', null);
INSERT INTO text VALUES ('SHARE_LINKEDIN_DESC', 'eu', 'SHARE', 'LinkedIn', null);
INSERT INTO text VALUES ('SHARE_VKONTAKTE_DESC', 'es', 'SHARE', 'Publicar en VKontakte', null);
INSERT INTO text VALUES ('SHARE_VKONTAKTE_DESC', 'en', 'SHARE', 'Share on VKontakte', null);
INSERT INTO text VALUES ('SHARE_VKONTAKTE_DESC', 'eu', 'SHARE', 'VKontakte', null);
INSERT INTO share VALUES (1, 1, 1, 'SHARE_FACEBOOK', 'SHARE_FACEBOOK_DESC', 'facebook.svg', 'https://www.facebook.com/sharer/sharer.php?u=');
INSERT INTO share VALUES (2, 2, 1, 'SHARE_X', 'SHARE_X_DESC', 'x.svg', 'https://x.com/share?url=');
INSERT INTO share VALUES (3, 4, 1, 'SHARE_TELEGRAM', 'SHARE_TELEGRAM_DESC', 'telegramn.svg', 'https://t.me/share/url?url=');
INSERT INTO share VALUES (4, 5, 1, 'SHARE_LINKEDIN', 'SHARE_LINKEDIN_DESC', 'linkedin.svg', 'https://www.linkedin.com/shareArticle?mini=true&url=');
INSERT INTO share VALUES (5, 6, 1, 'SHARE_VKONTAKTE', 'SHARE_VKONTAKTE_DESC', 'vkontakte.svg', 'http://vk.com/share.php?url=');

-- TAGS
INSERT INTO text VALUES ('TAG_JS',      'es', 'TAG', 'Javascript', null);
INSERT INTO text VALUES ('TAG_JS',      'en', 'TAG', 'Javascript', null);
INSERT INTO text VALUES ('TAG_JS',      'eu', 'TAG', 'Javascript', null);
INSERT INTO text VALUES ('TAG_HTML5',   'es', 'TAG', 'HTML5', null);
INSERT INTO text VALUES ('TAG_HTML5',   'en', 'TAG', 'HTML5', null);
INSERT INTO text VALUES ('TAG_HTML5',   'eu', 'TAG', 'HTML5', null);
INSERT INTO text VALUES ('TAG_ANDROID', 'es', 'TAG', 'Android', null);
INSERT INTO text VALUES ('TAG_ANDROID', 'en', 'TAG', 'Android', null);
INSERT INTO text VALUES ('TAG_ANDROID', 'eu', 'TAG', 'Android', null);
INSERT INTO text VALUES ('TAG_IOS',     'es', 'TAG', 'iOS', null);
INSERT INTO text VALUES ('TAG_IOS',     'en', 'TAG', 'iOS', null);
INSERT INTO text VALUES ('TAG_IOS',     'eu', 'TAG', 'iOS', null);
INSERT INTO text VALUES ('TAG_JAVA',    'es', 'TAG', 'Java', null);
INSERT INTO text VALUES ('TAG_JAVA',    'en', 'TAG', 'Java', null);
INSERT INTO text VALUES ('TAG_JAVA',    'eu', 'TAG', 'Java', null);
INSERT INTO text VALUES ('TAG_SWIFT',   'es', 'TAG', 'Swift', null);
INSERT INTO text VALUES ('TAG_SWIFT',   'en', 'TAG', 'Swift', null);
INSERT INTO text VALUES ('TAG_SWIFT',   'eu', 'TAG', 'Swift', null);
INSERT INTO text VALUES ('TAG_WEB',     'es', 'TAG', 'Web', null);
INSERT INTO text VALUES ('TAG_WEB',     'en', 'TAG', 'Web', null);
INSERT INTO text VALUES ('TAG_WEB',     'eu', 'TAG', 'Web', null);
INSERT INTO text VALUES ('TAG_CPP',     'es', 'TAG', 'C++', null);
INSERT INTO text VALUES ('TAG_CPP',     'en', 'TAG', 'C++', null);
INSERT INTO text VALUES ('TAG_CPP',     'eu', 'TAG', 'C++', null);
INSERT INTO text VALUES ('TAG_OGRE',    'es', 'TAG', 'OGRE', null);
INSERT INTO text VALUES ('TAG_OGRE',    'en', 'TAG', 'OGRE', null);
INSERT INTO text VALUES ('TAG_OGRE',    'eu', 'TAG', 'OGRE', null);
INSERT INTO text VALUES ('TAG_PHP',     'es', 'TAG', 'PHP', null);
INSERT INTO text VALUES ('TAG_PHP',     'en', 'TAG', 'PHP', null);
INSERT INTO text VALUES ('TAG_PHP',     'eu', 'TAG', 'PHP', null);

-- PAGE footer
INSERT INTO text VALUES ('FOOTER_FOLLOW', 'es', 'FOOTER', 'Sígueme', null);
INSERT INTO text VALUES ('FOOTER_COPY',   'es', 'FOOTER', 'Copyright Iñigo Valentin 2014 - #YEAR#', null);
INSERT INTO text VALUES ('FOOTER_HELP',   'es', 'FOOTER', 'Ayuda', null);
INSERT INTO text VALUES ('FOOTER_FOLLOW', 'en', 'FOOTER', 'Follow me', null);
INSERT INTO text VALUES ('FOOTER_COPY',   'en', 'FOOTER', 'Copyright Iñigo Valentin 2014 - #YEAR#', null);
INSERT INTO text VALUES ('FOOTER_HELP',   'en', 'FOOTER', 'Help', null);
INSERT INTO text VALUES ('FOOTER_FOLLOW', 'eu', 'FOOTER', 'Jarraitu', null);
INSERT INTO text VALUES ('FOOTER_COPY',   'eu', 'FOOTER', 'Copyright Iñigo Valentin 2014 - #YEAR#', null);
INSERT INTO text VALUES ('FOOTER_HELP',   'eu', 'FOOTER', 'Laguntza', null);


-- PAGE index
INSERT INTO text VALUES ('INDEX_PROFILE',      'es', 'INDEX', 'Yo', null);
INSERT INTO text VALUES ('INDEX_PROFILE',      'en', 'INDEX', 'Me', null);
INSERT INTO text VALUES ('INDEX_PROFILE',      'eu', 'INDEX', 'Ni', null);
INSERT INTO text VALUES ('INDEX_PROFILE_MAIL', 'es', 'INDEX', 'Contacta', null);
INSERT INTO text VALUES ('INDEX_PROFILE_MAIL', 'en', 'INDEX', 'Contact me', null);
INSERT INTO text VALUES ('INDEX_PROFILE_MAIL', 'eu', 'INDEX', 'Jarri harremanetan', null);
INSERT INTO text VALUES ('INDEX_PROFILE_MORE', 'es', 'INDEX', 'Más sobre mi', null);
INSERT INTO text VALUES ('INDEX_PROFILE_MORE', 'en', 'INDEX', 'More about me', null);
INSERT INTO text VALUES ('INDEX_PROFILE_MORE', 'eu', 'INDEX', 'Ni', null);
INSERT INTO text VALUES ('INDEX_PROFILE_CV',   'es', 'INDEX', 'CV', null);
INSERT INTO text VALUES ('INDEX_PROFILE_CV',   'en', 'INDEX', 'Résumé', null);
INSERT INTO text VALUES ('INDEX_PROFILE_CV',   'eu', 'INDEX', 'CV', null);
INSERT INTO text VALUES ('INDEX_PROJECTS',     'es', 'INDEX', 'Proyectos', null);
INSERT INTO text VALUES ('INDEX_PROJECTS',     'en', 'INDEX', 'Projects', null);
INSERT INTO text VALUES ('INDEX_PROJECTS',     'eu', 'INDEX', 'Proiektuak', null);
INSERT INTO text VALUES ('INDEX_PROJECTS_ALL', 'es', 'INDEX', 'Ver todos', null);
INSERT INTO text VALUES ('INDEX_PROJECTS_ALL', 'en', 'INDEX', 'See all projects', null);
INSERT INTO text VALUES ('INDEX_PROJECTS_ALL', 'eu', 'INDEX', 'Denak ikusi', null);


-- PAGE project
INSERT INTO text VALUES ('PROJECT_TITLE',           'es', 'PROJECT', 'Proyectos', null);
INSERT INTO text VALUES ('PROJECT_TITLE',           'en', 'PROJECT', 'Projects', null);
INSERT INTO text VALUES ('PROJECT_TITLE',           'eu', 'PROJECT', 'Projektuak', null);
INSERT INTO text VALUES ('PROJECT_DESCRIPTION',     'es', 'PROJECT', '', null); --TODO
INSERT INTO text VALUES ('PROJECT_DESCRIPTION',     'en', 'PROJECT', '', null); --TODO
INSERT INTO text VALUES ('PROJECT_DESCRIPTION',     'eu', 'PROJECT', '', null); --TODO
INSERT INTO text VALUES ('PROJECT_SEARCH',          'es', 'PROJECT', 'Buscar', null);
INSERT INTO text VALUES ('PROJECT_SEARCH',          'en', 'PROJECT', 'Search', null);
INSERT INTO text VALUES ('PROJECT_SEARCH',          'eu', 'PROJECT', 'Bilatu', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_ADVANCED', 'es', 'PROJECT', 'Búsqueda avanzada', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_ADVANCED', 'en', 'PROJECT', 'Advanced search', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_ADVANCED', 'eu', 'PROJECT', 'Búsqueda avanzada', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_TYPE',     'es', 'PROJECT', 'Tipo', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_TYPE',     'en', 'PROJECT', 'Project type', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_TYPE',     'eu', 'PROJECT', 'Tipu', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_LICENSE',  'es', 'PROJECT', 'Licencia', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_LICENSE',  'en', 'PROJECT', 'License', null);
INSERT INTO text VALUES ('PROJECT_SEARCH_LICENSE',  'eu', 'PROJECT', 'Lizenzia', null);
INSERT INTO text VALUES ('PROJECT_VERSION',         'es', 'PROJECT', 'Versión', null);
INSERT INTO text VALUES ('PROJECT_VERSION',         'en', 'PROJECT', 'Version', null);
INSERT INTO text VALUES ('PROJECT_VERSION',         'eu', 'PROJECT', 'Versión', null);
INSERT INTO text VALUES ('PROJECT_CLOSE',           'es', 'PROJECT', 'Cerrar', null);
INSERT INTO text VALUES ('PROJECT_CLOSE',           'en', 'PROJECT', 'Close', null);
INSERT INTO text VALUES ('PROJECT_CLOSE',           'eu', 'PROJECT', 'Itxali', null);
INSERT INTO text VALUES ('PROJECT_INFO',            'es', 'PROJECT', 'Detalles', null);
INSERT INTO text VALUES ('PROJECT_INFO',            'en', 'PROJECT', 'Details', null);
INSERT INTO text VALUES ('PROJECT_INFO',            'eu', 'PROJECT', 'Informazioa', null);
INSERT INTO text VALUES ('PROJECT_TAGS',            'es', 'PROJECT', 'Tags', null);
INSERT INTO text VALUES ('PROJECT_TAGS',            'en', 'PROJECT', 'Tags', null);
INSERT INTO text VALUES ('PROJECT_TAGS',            'eu', 'PROJECT', 'Tags', null);
INSERT INTO text VALUES ('PROJECT_LICENSE',         'es', 'PROJECT', 'License', null);
INSERT INTO text VALUES ('PROJECT_LICENSE',         'en', 'PROJECT', 'Licencia', null);
INSERT INTO text VALUES ('PROJECT_LICENSE',         'eu', 'PROJECT', 'Lizentzia', null);
INSERT INTO text VALUES ('PROJECT_LICENSE_SUMMARY', 'es', 'PROJECT', 'En resumen:', null);
INSERT INTO text VALUES ('PROJECT_LICENSE_SUMMARY', 'en', 'PROJECT', 'In a few words:', null);
INSERT INTO text VALUES ('PROJECT_LICENSE_SUMMARY', 'eu', 'PROJECT', 'En resumen:', null);
INSERT INTO text VALUES ('PROJECT_LICENSE_LEGAL',   'es', 'PROJECT', 'Texto completo:', null);
INSERT INTO text VALUES ('PROJECT_LICENSE_LEGAL',   'en', 'PROJECT', 'Full legal text:', null);
INSERT INTO text VALUES ('PROJECT_LICENSE_LEGAL',   'eu', 'PROJECT', 'Textu osoa:', null);
INSERT INTO text VALUES ('PROJECT_COMMENT',         'es', 'PROJECT', 'Notas de $', null);
INSERT INTO text VALUES ('PROJECT_COMMENT',         'en', 'PROJECT', "$'s notes", null);
INSERT INTO text VALUES ('PROJECT_COMMENT',         'eu', 'PROJECT', '$ren oharrak', null);


-- PAGE profile
INSERT INTO text VALUES ('PROFILE_TITLE',            'es', 'PROFILE', 'Yo', null);
INSERT INTO text VALUES ('PROFILE_TITLE',            'en', 'PROFILE', 'Me', null);
INSERT INTO text VALUES ('PROFILE_TITLE',            'eu', 'PROFILE', 'Ni', null);
INSERT INTO text VALUES ('PROFILE_DESCRIPTION',      'es', 'PROFILE', 'Sobre mí', null);
INSERT INTO text VALUES ('PROFILE_DESCRIPTION',      'en', 'PROFILE', 'About me', null);
INSERT INTO text VALUES ('PROFILE_DESCRIPTION',      'eu', 'PROFILE', 'Niri buruz', null);
INSERT INTO text VALUES ('PROFILE_DOWNLOAD_CURRENT', 'es', 'PROFILE', 'Descargar en castellano', null);
INSERT INTO text VALUES ('PROFILE_DOWNLOAD_CURRENT', 'en', 'PROFILE', 'Download in english', null);
INSERT INTO text VALUES ('PROFILE_DOWNLOAD_CURRENT', 'eu', 'PROFILE', 'Euzkaraz deskargatu', null);
INSERT INTO text VALUES ('PROFILE_DOWNLOAD_OTHER',   'es', 'PROFILE', 'Descargar en otros idiomas', null);
INSERT INTO text VALUES ('PROFILE_DOWNLOAD_OTHER',   'en', 'PROFILE', 'Download in other languages', null);
INSERT INTO text VALUES ('PROFILE_DOWNLOAD_OTHER',   'eu', 'PROFILE', 'Beste hizkuntzetan deskargatu', null);
INSERT INTO text VALUES ('PROFILE_CV',               'es', 'PROFILE', 'CV', null);
INSERT INTO text VALUES ('PROFILE_CV',               'en', 'PROFILE', 'Résumé', null);
INSERT INTO text VALUES ('PROFILE_CV',               'eu', 'PROFILE', 'Résumé', null);
INSERT INTO text VALUES ('PROFILE_CV_PRINTABLE',     'es', 'PROFILE', 'Ver en formato imprimible', null);
INSERT INTO text VALUES ('PROFILE_CV_PRINTABLE',     'en', 'PROFILE', 'View printable format', null);
INSERT INTO text VALUES ('PROFILE_CV_PRINTABLE',     'eu', 'PROFILE', 'Résumé', null);
INSERT INTO text VALUES ('PROFILE_CV_LANG',          'es', 'PROFILE', 'Otros idiomas', null);
INSERT INTO text VALUES ('PROFILE_CV_LANG',          'en', 'PROFILE', 'Other languages', null);
INSERT INTO text VALUES ('PROFILE_CV_LANG',          'eu', 'PROFILE', 'Beste hizkuntzak', null);
INSERT INTO text VALUES ('PROFILE_SKILLS',           'es', 'PROFILE', 'Habilidades', null);
INSERT INTO text VALUES ('PROFILE_SKILLS',           'en', 'PROFILE', 'Skills', null);
INSERT INTO text VALUES ('PROFILE_SKILLS',           'eu', 'PROFILE', 'Habilitateak', null);

-- PAGE help
INSERT INTO text VALUES ('HELP_TITLE', 'es', 'HELP', 'Ayuda', null);
INSERT INTO text VALUES ('HELP_TITLE', 'en', 'HELP', 'Help', null);
INSERT INTO text VALUES ('HELP_TITLE', 'eu', 'HELP', 'Laguntza', null);
INSERT INTO text VALUES ('HELP_DESCRIPTION', 'es', 'HELP', 'Ayuda', null);
INSERT INTO text VALUES ('HELP_DESCRIPTION', 'en', 'HELP', 'Help', null);
INSERT INTO text VALUES ('HELP_DESCRIPTION', 'eu', 'HELP', 'Laguntza', null);
INSERT INTO text VALUES ('HELP_INFO_TITLE', 'es', 'HELP', 'Ayuda', null);
INSERT INTO text VALUES ('HELP_INFO_TITLE', 'en', 'HELP', 'Help', null);
INSERT INTO text VALUES ('HELP_INFO_TITLE', 'eu', 'HELP', 'Laguntza', null);
INSERT INTO text VALUES ('HELP_LICENSE_TITLE', 'es', 'HELP', 'Licencias', null);
INSERT INTO text VALUES ('HELP_LICENSE_TITLE', 'en', 'HELP', 'Licenses', null);
INSERT INTO text VALUES ('HELP_LICENSE_TITLE', 'eu', 'HELP', 'Lizentziak', null);
INSERT INTO text VALUES ('HELP_PRIVACY_TITLE', 'es', 'HELP', 'Privacidad', null);
INSERT INTO text VALUES ('HELP_PRIVACY_TITLE', 'en', 'HELP', 'Privacy', null);
INSERT INTO text VALUES ('HELP_PRIVACY_TITLE', 'eu', 'HELP', 'Pribatutasuna', null);
INSERT INTO text VALUES ('HELP_COOKIES_TITLE', 'es', 'HELP', 'Cookies', null);
INSERT INTO text VALUES ('HELP_COOKIES_TITLE', 'en', 'HELP', 'Cookies', null);
INSERT INTO text VALUES ('HELP_COOKIES_TITLE', 'eu', 'HELP', 'Cookiak', null);
INSERT INTO text VALUES ('HELP_POLICY', 'es', 'HELP', 'Política de privacidad', null);
INSERT INTO text VALUES ('HELP_POLICY', 'en', 'HELP', 'Privacy Policy', null);
INSERT INTO text VALUES ('HELP_POLICY', 'eu', 'HELP', 'Pribatutasun Politika', null);

-- PAGE error
INSERT INTO text VALUES ('ERROR_TITLE',           'es', 'ERROR', 'Error', null);
INSERT INTO text VALUES ('ERROR_TITLE',           'en', 'ERROR', 'Error', null);
INSERT INTO text VALUES ('ERROR_TITLE',           'eu', 'ERROR', 'Errorea', null);
INSERT INTO text VALUES ('ERROR_ERROR',           'es', 'ERROR', 'ERROR', null);
INSERT INTO text VALUES ('ERROR_ERROR',           'en', 'ERROR', 'ERROR', null);
INSERT INTO text VALUES ('ERROR_ERROR',           'eu', 'ERROR', 'ERROR', null);
INSERT INTO text VALUES ('ERROR_CODE',            'es', 'ERROR', 'CODE', null);
INSERT INTO text VALUES ('ERROR_CODE',            'en', 'ERROR', 'CODE', null);
INSERT INTO text VALUES ('ERROR_CODE',            'eu', 'ERROR', 'CODE', null);
INSERT INTO text VALUES ('ERROR_400_TITLE',       'es', 'ERROR', 'Bad request', null);
INSERT INTO text VALUES ('ERROR_400_TITLE',       'en', 'ERROR', 'Bad request', null);
INSERT INTO text VALUES ('ERROR_400_TITLE',       'eu', 'ERROR', 'Bad request', null);
INSERT INTO text VALUES ('ERROR_400_DESCRIPTION', 'es', 'ERROR', 'La solicitud se ha recibido con errores... y no se como responder.', null);
INSERT INTO text VALUES ('ERROR_400_DESCRIPTION', 'en', 'ERROR', 'This server doesn''t understand your request.', null);
INSERT INTO text VALUES ('ERROR_400_DESCRIPTION', 'eu', 'ERROR', 'La solicitud se ha recibido con errores... y no se como responder.', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION',    'es', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION',    'en', 'ERROR', 'Try a solution:', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION',    'eu', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_0',  'es', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_0',  'en', 'ERROR', 'Go to the previous page', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_0',  'eu', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_1',  'es', 'ERROR', 'Ir a la página principal', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_1',  'en', 'ERROR', 'Go to the main page', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_1',  'eu', 'ERROR', 'Ir a la página principal', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_2',  'es', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_2',  'en', 'ERROR', 'Watch cute cat videos in Youtube', null);
INSERT INTO text VALUES ('ERROR_400_SOLUTION_2',  'eu', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_401_TITLE',       'es', 'ERROR', 'Sin autorización', null);
INSERT INTO text VALUES ('ERROR_401_TITLE',       'en', 'ERROR', 'Unauthorized', null);
INSERT INTO text VALUES ('ERROR_401_TITLE',       'eu', 'ERROR', 'Sin autorización', null);
INSERT INTO text VALUES ('ERROR_401_DESCRIPTION', 'es', 'ERROR', 'Estás intentando ver algo que no debes. No soy muy de prohibir, así que lo má probable es que sea algo momentaneo.', null);
INSERT INTO text VALUES ('ERROR_401_DESCRIPTION', 'en', 'ERROR', 'You are trying to see something you are not supposed to.', null);
INSERT INTO text VALUES ('ERROR_401_DESCRIPTION', 'eu', 'ERROR', 'Estás intentando ver algo que no debes. No soy muy de prohibir, así que lo má probable es que sea algo momentaneo.', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION',    'es', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION',    'en', 'ERROR', 'Try a solution:', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION',    'eu', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_0',  'es', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_0',  'en', 'ERROR', 'Go to the previous page', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_0',  'eu', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_1',  'es', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_1',  'en', 'ERROR', 'Go to the main page', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_1',  'eu', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_2',  'es', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_2',  'en', 'ERROR', 'Watch cute cat videos in Youtube', null);
INSERT INTO text VALUES ('ERROR_401_SOLUTION_2',  'eu', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_403_TITLE',       'es', 'ERROR', 'Prohibido', null);
INSERT INTO text VALUES ('ERROR_403_TITLE',       'en', 'ERROR', 'Forbidden', null);
INSERT INTO text VALUES ('ERROR_403_TITLE',       'eu', 'ERROR', 'Debekatuta', null);
INSERT INTO text VALUES ('ERROR_403_DESCRIPTION', 'es', 'ERROR', 'Estás intentando ver algo que no debes. No soy muy de prohibir, así que lo má probable es que sea algo momentaneo.', null);
INSERT INTO text VALUES ('ERROR_403_DESCRIPTION', 'en', 'ERROR', 'You are trying to see something you are not supposed to.', null);
INSERT INTO text VALUES ('ERROR_403_DESCRIPTION', 'eu', 'ERROR', 'Estás intentando ver algo que no debes. No soy muy de prohibir, así que lo má probable es que sea algo momentaneo.', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION',    'es', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION',    'en', 'ERROR', 'Try a solution:', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION',    'eu', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_0',  'es', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_0',  'en', 'ERROR', 'Go to the previous page', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_0',  'eu', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_1',  'es', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_1',  'en', 'ERROR', 'Go to the main page', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_1',  'eu', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_2',  'es', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_2',  'en', 'ERROR', 'Watch cute cat videos in Youtube', null);
INSERT INTO text VALUES ('ERROR_403_SOLUTION_2',  'eu', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_404_TITLE',       'es', 'ERROR', 'No enconrtado', null);
INSERT INTO text VALUES ('ERROR_404_TITLE',       'en', 'ERROR', 'Not found', null);
INSERT INTO text VALUES ('ERROR_404_TITLE',       'eu', 'ERROR', 'No enconrtado', null);
INSERT INTO text VALUES ('ERROR_404_DESCRIPTION', 'es', 'ERROR', 'La página que buscas no existe en este universo. Inténtalo en uno diferente.', null);
INSERT INTO text VALUES ('ERROR_404_DESCRIPTION', 'en', 'ERROR', 'Sorry. The page you are looking for doesn&#39;t exist in this universe. Try in an alternate one.', null);
INSERT INTO text VALUES ('ERROR_404_DESCRIPTION', 'eu', 'ERROR', 'La página que buscas no existe en este universo. Inténtalo en uno diferente.', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION',    'es', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION',    'en', 'ERROR', 'Try a solution:', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION',    'eu', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_0',  'es', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_0',  'en', 'ERROR', 'Go to the previous page', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_0',  'eu', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_1',  'es', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_1',  'en', 'ERROR', 'Go to the main page', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_1',  'eu', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_2',  'es', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_2',  'en', 'ERROR', 'Watch cute cat videos in Youtube', null);
INSERT INTO text VALUES ('ERROR_404_SOLUTION_2',  'eu', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_500_TITLE',       'es', 'ERROR', 'Error del servidor', null);
INSERT INTO text VALUES ('ERROR_500_TITLE',       'en', 'ERROR', 'Server error', null);
INSERT INTO text VALUES ('ERROR_500_TITLE',       'eu', 'ERROR', 'Errorea serbidorean', null);
INSERT INTO text VALUES ('ERROR_500_DESCRIPTION', 'es', 'ERROR', 'La he liado parda. El fallo está en mi lado, pero no te preocupes, ahorá mismo el informático estará sudando tinta gorda para arreglarlo.', null);
INSERT INTO text VALUES ('ERROR_500_DESCRIPTION', 'en', 'ERROR', 'This one is on me: I&#39;ve messed something up. Sorry! I&#39;m probably trying to fix it right now.', null);
INSERT INTO text VALUES ('ERROR_500_DESCRIPTION', 'eu', 'ERROR', 'La he liado parda. El fallo está en mi lado, pero no te preocupes, ahorá mismo el informático estará sudando tinta gorda para arreglarlo.', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION',    'es', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION',    'en', 'ERROR', 'Try a solution:', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION',    'eu', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_0',  'es', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_0',  'en', 'ERROR', 'Go to the previous page', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_0',  'eu', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_1',  'es', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_1',  'en', 'ERROR', 'Go to the main page', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_1',  'eu', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_2',  'es', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_2',  'en', 'ERROR', 'Watch cute cat videos in Youtube', null);
INSERT INTO text VALUES ('ERROR_500_SOLUTION_2',  'eu', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_XXX_TITLE',       'es', 'ERROR', 'Error inesperado', null);
INSERT INTO text VALUES ('ERROR_XXX_TITLE',       'en', 'ERROR', 'Unexpected error', null);
INSERT INTO text VALUES ('ERROR_XXX_TITLE',       'eu', 'ERROR', 'Error inesperado', null);
INSERT INTO text VALUES ('ERROR_XXX_DESCRIPTION', 'es', 'ERROR', 'Algo ha ido mal...', null);
INSERT INTO text VALUES ('ERROR_XXX_DESCRIPTION', 'en', 'ERROR', 'Something went wrong...', null);
INSERT INTO text VALUES ('ERROR_XXX_DESCRIPTION', 'eu', 'ERROR', 'Algo ha ido mal...', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION',    'es', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION',    'en', 'ERROR', 'Try a solution:', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION',    'eu', 'ERROR', 'Prueba una solución:', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_0',  'es', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_0',  'en', 'ERROR', 'Go to the previous page', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_0',  'eu', 'ERROR', 'Volver a la página anterior', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_1',  'es', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_1',  'en', 'ERROR', 'Go to the main page', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_1',  'eu', 'ERROR', 'Ir a la pá principal', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_2',  'es', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_2',  'en', 'ERROR', 'Watch cute cat videos in Youtube', null);
INSERT INTO text VALUES ('ERROR_XXX_SOLUTION_2',  'eu', 'ERROR', 'Ver vídeos de gatitos en Youtube', null);


-- TABLE project_type
INSERT INTO text VALUES ('PROJECT_TYPE_D',         'es', 'DB_PROJECT_TYPE', 'Desarrollo', null);
INSERT INTO text VALUES ('PROJECT_TYPE_D',         'en', 'DB_PROJECT_TYPE', 'Development', null);
INSERT INTO text VALUES ('PROJECT_TYPE_D',         'eu', 'DB_PROJECT_TYPE', 'Development', null);
INSERT INTO text VALUES ('PROJECT_TYPE_D_SUMMARY', 'es', 'DB_PROJECT_TYPE', 'Desarrollo', null);
INSERT INTO text VALUES ('PROJECT_TYPE_D_SUMMARY', 'en', 'DB_PROJECT_TYPE', 'Development', null);
INSERT INTO text VALUES ('PROJECT_TYPE_D_SUMMARY', 'eu', 'DB_PROJECT_TYPE', 'Development', null);
INSERT INTO text VALUES ('PROJECT_TYPE_S',         'es', 'DB_PROJECT_TYPE', 'Sistemas', null);
INSERT INTO text VALUES ('PROJECT_TYPE_S',         'en', 'DB_PROJECT_TYPE', 'System', null);
INSERT INTO text VALUES ('PROJECT_TYPE_S',         'eu', 'DB_PROJECT_TYPE', 'System', null);
INSERT INTO text VALUES ('PROJECT_TYPE_S_SUMMARY', 'es', 'DB_PROJECT_TYPE', 'Sistemas', null);
INSERT INTO text VALUES ('PROJECT_TYPE_S_SUMMARY', 'en', 'DB_PROJECT_TYPE', 'System', null);
INSERT INTO text VALUES ('PROJECT_TYPE_S_SUMMARY', 'eu', 'DB_PROJECT_TYPE', 'System', null);
INSERT INTO project_type VALUES ('D', 'PROJECT_TYPE_D', 'PROJECT_TYPE_D_SUMMARY');
INSERT INTO project_type VALUES ('S', 'PROJECT_TYPE_S', 'PROJECT_TYPE_S_SUMMARY');


-- TABLE project_url_type
INSERT INTO text VALUES ('URL_TYPE_W',         'es', 'DB_URL_TYPE', 'Ver sitio web', null);
INSERT INTO text VALUES ('URL_TYPE_W',         'en', 'DB_URL_TYPE', 'Go to web site', null);
INSERT INTO text VALUES ('URL_TYPE_W',         'eu', 'DB_URL_TYPE', 'Horrialdera', null);
INSERT INTO text VALUES ('URL_TYPE_W_SUMMARY', 'es', 'DB_URL_TYPE', 'Ver sitio wew de este proyecto.', null);
INSERT INTO text VALUES ('URL_TYPE_W_SUMMARY', 'en', 'DB_URL_TYPE', 'See web site.', null);
INSERT INTO text VALUES ('URL_TYPE_W_SUMMARY', 'eu', 'DB_URL_TYPE', 'Horrialdera.', null);
INSERT INTO text VALUES ('URL_TYPE_P',         'es', 'DB_URL_TYPE', 'Google Play', null);
INSERT INTO text VALUES ('URL_TYPE_P',         'en', 'DB_URL_TYPE', 'Google Play', null);
INSERT INTO text VALUES ('URL_TYPE_P',         'eu', 'DB_URL_TYPE', 'Google Play', null);
INSERT INTO text VALUES ('URL_TYPE_P_SUMMARY', 'es', 'DB_URL_TYPE', 'Ver app en Google Play.', null);
INSERT INTO text VALUES ('URL_TYPE_P_SUMMARY', 'en', 'DB_URL_TYPE', 'See on Google Play.', null);
INSERT INTO text VALUES ('URL_TYPE_P_SUMMARY', 'eu', 'DB_URL_TYPE', 'Google Play-n.', null);
INSERT INTO text VALUES ('URL_TYPE_A',         'es', 'DB_URL_TYPE', 'App Store', null);
INSERT INTO text VALUES ('URL_TYPE_A',         'en', 'DB_URL_TYPE', 'App Store', null);
INSERT INTO text VALUES ('URL_TYPE_A',         'eu', 'DB_URL_TYPE', 'App Store', null);
INSERT INTO text VALUES ('URL_TYPE_A_SUMMARY', 'es', 'DB_URL_TYPE', 'Ver app en App Store.', null);
INSERT INTO text VALUES ('URL_TYPE_A_SUMMARY', 'en', 'DB_URL_TYPE', 'See on App Store.', null);
INSERT INTO text VALUES ('URL_TYPE_A_SUMMARY', 'eu', 'DB_URL_TYPE', 'App Store-an.', null);
INSERT INTO text VALUES ('URL_TYPE_G',         'es', 'DB_URL_TYPE', 'Github', null);
INSERT INTO text VALUES ('URL_TYPE_G',         'en', 'DB_URL_TYPE', 'Github', null);
INSERT INTO text VALUES ('URL_TYPE_G',         'eu', 'DB_URL_TYPE', 'Github', null);
INSERT INTO text VALUES ('URL_TYPE_G_SUMMARY', 'es', 'DB_URL_TYPE', 'Ver código fuente en Github.', null);
INSERT INTO text VALUES ('URL_TYPE_G_SUMMARY', 'en', 'DB_URL_TYPE', 'Checkout source code on Github.', null);
INSERT INTO text VALUES ('URL_TYPE_G_SUMMARY', 'eu', 'DB_URL_TYPE', 'Kodea Github-n.', null);
INSERT INTO text VALUES ('URL_TYPE_M',         'es', 'DB_URL_TYPE', 'Ver', null);
INSERT INTO text VALUES ('URL_TYPE_M',         'en', 'DB_URL_TYPE', 'See', null);
INSERT INTO text VALUES ('URL_TYPE_M',         'eu', 'DB_URL_TYPE', 'Ikusi', null);
INSERT INTO text VALUES ('URL_TYPE_M_SUMMARY', 'es', 'DB_URL_TYPE', 'Ver', null);
INSERT INTO text VALUES ('URL_TYPE_M_SUMMARY', 'en', 'DB_URL_TYPE', 'See', null);
INSERT INTO text VALUES ('URL_TYPE_M_SUMMARY', 'eu', 'DB_URL_TYPE', 'Ikusi', null);
INSERT INTO project_url_type VALUES ('E', null, null, null);
INSERT INTO project_url_type VALUES ('W', 'URL_TYPE_W', 'URL_TYPE_W_SUMMARY', 'web.svg');
INSERT INTO project_url_type VALUES ('P', 'URL_TYPE_P', 'URL_TYPE_P_SUMMARY', 'google_play.svg');
INSERT INTO project_url_type VALUES ('A', 'URL_TYPE_A', 'URL_TYPE_A_SUMMARY', 'app_store.svg');
INSERT INTO project_url_type VALUES ('G', 'URL_TYPE_G', 'URL_TYPE_G_SUMMARY', 'github.svg');
INSERT INTO project_url_type VALUES ('M', 'URL_TYPE_M', 'URL_TYPE_M_SUMMARY', 'misc.svg');



-- TABLE license
INSERT INTO text VALUES ('LICENSE_CC-BY-SA_SUMMARY', 'es', 'LICENSE', null, 'LICENSE_CC-BY-SA_SUMMARY__ES');
INSERT INTO text VALUES ('LICENSE_CC-BY-SA_SUMMARY', 'en', 'LICENSE', null, 'LICENSE_CC-BY-SA_SUMMARY__EN');
INSERT INTO text VALUES ('LICENSE_CC-BY-SA_SUMMARY', 'eu', 'LICENSE', null, 'LICENSE_CC-BY-SA_SUMMARY__EU');
INSERT INTO text VALUES ('LICENSE_CC-BY-SA',         'es', 'LICENSE', null, 'LICENSE_CC-BY-SA__ES');
INSERT INTO text VALUES ('LICENSE_CC-BY-SA',         'en', 'LICENSE', null, 'LICENSE_CC-BY-SA__EN');
INSERT INTO text VALUES ('LICENSE_CC-BY-SA',         'eu', 'LICENSE', null, 'LICENSE_CC-BY-SA__EU');
INSERT INTO text VALUES ('LICENSE_GPLV3_SUMMARY',    'es', 'LICENSE', null, 'LICENSE_GPLV3_SUMMARY__ES');
INSERT INTO text VALUES ('LICENSE_GPLV3_SUMMARY',    'en', 'LICENSE', null, 'LICENSE_GPLV3_SUMMARY__EN');
INSERT INTO text VALUES ('LICENSE_GPLV3_SUMMARY',    'eu', 'LICENSE', null, 'LICENSE_GPLV3_SUMMARY__EU');
INSERT INTO text VALUES ('LICENSE_GPLV3',            'es', 'LICENSE', null, 'LICENSE_GPLV3__ES');
INSERT INTO text VALUES ('LICENSE_GPLV3',            'en', 'LICENSE', null, 'LICENSE_GPLV3__EN');
INSERT INTO text VALUES ('LICENSE_GPLV3',            'eu', 'LICENSE', null, 'LICENSE_GPLV3__EU');
INSERT INTO license VALUES ('CC-BY-SA', 'LICENSE_CC-BY-SA_SUMMARY', 'LICENSE_CC-BY-SA', 'CC-BY-SA.svg', 'CC-BY-SA.svg');
INSERT INTO license VALUES ('GPLv3',    'LICENSE_GPLV3_SUMMARY',    'LICENSE_GPLV3',    'GPLV3.svg',    'GPLV3.svg');
